# Generated by Django 2.2.7 on 2019-11-30 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20191130_0646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='created_at',
            new_name='updated_at',
        ),
    ]
